export const RESTART_ON_REMOUNT = '@@saga-injector/restart-on-remount';
export const DAEMON = '@@saga-injector/daemon';
export const ONCE_TILL_UNMOUNT = '@@saga-injector/once-till-unmount';

export const LAST_UPDATED_DATE = 'LAST_UPDATED_DATE';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';

export const LOGIN_INPROGRESS = 'LOGIN_INPROGRESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT = 'LOGOUT';

export const UPDATE_DATA = "UPDATE_DATA";
export const LOAD_DATA = "LOAD_DATA";
export const SEARCH_DATA = "SEARCH_DATA";
export const RECENT_LOADS = "RECENT_LOADS";
export const GET_RECENT = "GET_RECENT";
export const FAVORITE_LOADS = "FAVORITE_LOADS";
export const GET_FAVORITE = "GET_FAVORITE";
export const PROFILE_IMAGE_SET = "PROFILE_IMAGE_SET";
export const MANAGE_CARD_DATA = "MANAGE_CARD_DATA";
export const GET_MANAGE_CARD_DATA = "GET_MANAGE_CARD_DATA";
export const CARRIER_MANAGE_DATA = "CARRIER_MANAGE_DATA";
export const GET_CARRIER_MANAGE_DATA = "GET_CARRIER_MANAGE_DATA";
export const CARRIER_INSURANCE_DATA = "CARRIER_INSURANCE_DATA";
export const GET_CARRIER_INSURANCE_DATA = "GET_CARRIER_INSURANCE_DATA";
export const CARRIER_INSURANCE_DATA2 = "CARRIER_INSURANCE_DATA2";
export const GET_CARRIER_INSURANCE_DATA2 = "GET_CARRIER_INSURANCE_DATA2";
export const PERMISSION_ALERT_MESSAGE = "PERMISSION_ALERT_MESSAGE";
export const MYLOAD_CARD_DATA = "MYLOAD_CARD_DATA";
export const GET_MYLOAD_CARD_DATA = "GET_MYLOAD_CARD_DATA";
export const CLOSE_PERMISSION_ALERT = "CLOSE_PERMISSION_ALERT";
export const GET_CARRIER_CONTACT_DATA="GET_CARRIER_CONTACT_DATA";
export const CARRIER_CONTACT_DATA ="CARRIER_CONTACT_DATA"; 

export const UPDATE_GPS_COORDS = "UPDATE_GPS_COORDS";
export const UPDATE_NETWORK_STATUS = "UPDATE_NETWORK_STATUS";
export const UPDATE_DEVICE_INFO = "UPDATE_DEVICE_INFO";

export const GPS_TIME = 30000;

export const USER_PROFILE_DATA = "USER_PROFILE_DATA";
export const GET_USER_PROFILE_DATA = "GET_USER_PROFILE_DATA";












